stages:
  - build

build:
  stage: build
  only:
    - cicd-test  # 실제 브랜치 이름으로 변경
  before_script:
    - echo 'Build starts successfully!'
  script:
    - echo 'build start!'
  tags:
    - test-deploy