image: ubuntu:22.04

stages:
  - build
  - deploy

variables:
  DEPLOY_SERVER: "ubuntu@$SSH_HOST"
  DEPLOY_PATH: "/home/ubuntu/app"
  SPRING_PROFILE: "dev"

    # - 'which ssh-agent || ( apt-get install -y openssh-client )'
    # - eval $(ssh-agent -s)
    # - echo "$SSH_KEY_PEM" | tr -d '\r' | ssh-add - > /dev/null
    # - mkdir -p ~/.ssh
    # - chmod 700 ~/.ssh
    # - ssh-keyscan your-server-ip >> ~/.ssh/known_hosts
    # - chmod 644 ~/.ssh/known_hosts

build:
  stage: build
  before_script:

  - echo "init start"
  - apt-get update

  # 자바 17 설치
  - echo "install java"
  - apt-get install openjdk-17-jdk -y
  - java -version

  # 설치된 Java 실행 파일의 경로를 확인합니다
  - which java

  # Java 실행 파일의 실제 경로를 확인합니다
  - readlink -f $(which java)

  # JAVA_HOME 환경 변수 설정
  - export JAVA_HOME="$(readlink -f $(which java)"
  - export PATH="$JAVA_HOME/bin:$PATH"
  
  # JAVA_HOME과 PATH 확인
  - echo "JAVA_HOME is set to $JAVA_HOME"
  - echo "PATH is set to $PATH"

  # 빌드
  - echo 'build start'
  - cd backend/blur
  - chmod +x ./gradlew

  script:
    - ./gradlew --version
    - ./gradlew clean build
  artifacts:
    paths:
      - build/libs/*.jar
  tags:
    - blurrr-deploy
  # only:
    # - dev

deploy:
  stage: deploy
  script:
    - echo "Deploying the project"
    - scp build/libs/*.jar $DEPLOY_SERVER:$DEPLOY_PATH/
    - ssh $DEPLOY_SERVER "cd $DEPLOY_PATH && ./deploy.sh"
  environment:
    name: dev
  # only:
  #   - dev
  tags:
    - blurrr-deploy