image: ubuntu:22.04

stages:
  - init
  - build
  - deploy

variables:
  DEPLOY_SERVER: "ubuntu@$SSH_HOST"
  DEPLOY_PATH: "/home/ubuntu/app"
  SPRING_PROFILE: "dev"
  JAVA_HOME: "/usr/lib/jvm/java-17-openjdk"
  GRADLE_HOME: "/opt/gradle"
  PATH: "$JAVA_HOME/bin:$GRADLE_HOME/bin:$PATH"

init:
  stage: init
  script:
    - echo "init start"
    - apt-get update
    - echo "install java"
    - apt-get install -y wget unzip openjdk-17-jdk
    - echo "Setting up JAVA_HOME and PATH..."
    - java -version
    - echo "install gradle"
    - GRADLE_LATEST_VERSION=$(curl -s https://services.gradle.org/versions/current | jq -r '.version')
    - wget -q --show-progress -O gradle-${GRADLE_LATEST_VERSION}-bin.zip https://services.gradle.org/distributions/gradle-${GRADLE_LATEST_VERSION}-bin.zip
    - unzip -d /opt/gradle gradle-${GRADLE_LATEST_VERSION}-bin.zip
    - rm gradle-${GRADLE_LATEST_VERSION}-bin.zip
    # - 'which ssh-agent || ( apt-get install -y openssh-client )'
    # - eval $(ssh-agent -s)
    # - echo "$SSH_KEY_PEM" | tr -d '\r' | ssh-add - > /dev/null
    # - mkdir -p ~/.ssh
    # - chmod 700 ~/.ssh
    # - ssh-keyscan your-server-ip >> ~/.ssh/known_hosts
    # - chmod 644 ~/.ssh/known_hosts
  tags:
    - blurrr-deploy

build:
  stage: build
  before_script:
    - echo 'build start'
    - cd backend/blur
    - chmod +x ./gradlew
  script:
    - ./gradlew clean build
  artifacts:
    paths:
      - build/libs/*.jar
  tags:
    - blurrr-deploy
  # only:
    # - dev

deploy:
  stage: deploy
  script:
    - echo "Deploying the project"
    - scp target/*.jar $DEPLOY_SERVER:$DEPLOY_PATH/
    - ssh $DEPLOY_SERVER "cd $DEPLOY_PATH && ./deploy.sh"
  environment:
    name: dev
  # only:
  #   - dev
  tags:
    - blurrr-deploy