image: ubuntu:22.04

stages:
  - build
  - deploy

variables:
  DEPLOY_SERVER: "ubuntu@$SSH_HOST"
  DEPLOY_PATH: "/home/ubuntu/app"
  SPRING_PROFILE: "dev"

build:
  stage: build
  before_script:

  # 자바 17 설치
  - apt-get update
  - echo "install java"
  - apt-get install openjdk-17-jdk -y
  - java -version

  # JAVA_HOME 환경 변수 설정
  - export JAVA_HOME="/usr/lib/jvm/java-17-openjdk-amd64"
  - export PATH="$JAVA_HOME/bin:$PATH"
  
  # JAVA_HOME과 PATH 확인
  - echo "JAVA_HOME is set to $JAVA_HOME"
  - echo "PATH is set to $PATH"

  script:
    - echo 'build'
    - cd backend/blur
    - chmod +x ./gradlew
    - ./gradlew clean build -x test
    
  artifacts:
    paths:
      - backend/blur/build/libs/*.jar
    expire_in: 1 week
    
  tags:
    - blurrr-deploy
  # only:
    # - dev

deploy:
  stage: deploy
  before_script:
    
    - apt-get update
    - apt-get install openssh-client -y

    - echo "Setting up SSH key..."
    - mkdir -p ~/.ssh
    - echo "$SSH_KEY_PEM" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $DEPLOY_SERVER >> ~/.ssh/known_hosts

  # - 'which ssh-agent || ( apt-get install -y openssh-client )'
  # - eval $(ssh-agent -s)
  # - echo "$SSH_KEY_PEM" | tr -d '\r' | ssh-add - > /dev/null
  # - mkdir -p ~/.ssh
  # - chmod 700 ~/.ssh
  # - ssh-keyscan your-server-ip >> ~/.ssh/known_hosts
  # - chmod 644 ~/.ssh/known_hosts

  script:
    - echo "Deploying the project"
    - scp -i ~/.ssh/id_rsa backend/blur/build/libs/*.jar $DEPLOY_SERVER:$DEPLOY_PATH/
    - ssh -i ~/.ssh/id_rsa $DEPLOY_SERVER "cd $DEPLOY_PATH && ./deploy.sh"

  environment:
    name: dev
  # only:
  #   - dev
  tags:
    - blurrr-deploy