image: ubuntu:22.04

stages:
  - init
  - build
  - deploy

variables:
  DEPLOY_SERVER: "ubuntu@$SSH_HOST"
  DEPLOY_PATH: "/home/ubuntu/app"
  SPRING_PROFILE: "dev"

init:
  stage: init
  script:
    - echo "init start"
    - apt-get update
    - echo "install java"
    - apt-get install openjdk-17-jdk -y
    - echo "Setting up JAVA_HOME and PATH..."
    - java -version
    # - 'which ssh-agent || ( apt-get install -y openssh-client )'
    # - eval $(ssh-agent -s)
    # - echo "$SSH_KEY_PEM" | tr -d '\r' | ssh-add - > /dev/null
    # - mkdir -p ~/.ssh
    # - chmod 700 ~/.ssh
    # - ssh-keyscan your-server-ip >> ~/.ssh/known_hosts
    # - chmod 644 ~/.ssh/known_hosts
  tags:
    - blurrr-deploy

build:
  variables:
    JAVA_HOME: "/usr/lib/jvm/java-17-openjdk-amd64"
    PATH: "$JAVA_HOME/bin:$PATH"
  stage: build
  before_script:
    - echo "JAVA_HOME is set to $JAVA_HOME"
    - echo "PATH is set to $PATH"
    - echo 'build start'
    - cd backend/blur
    - chmod +x ./gradlew
  script:
    - ./gradlew --version
    - ./gradlew clean build
  artifacts:
    paths:
      - build/libs/*.jar
  tags:
    - blurrr-deploy
  # only:
    # - dev

deploy:
  stage: deploy
  script:
    - echo "Deploying the project"
    - scp target/*.jar $DEPLOY_SERVER:$DEPLOY_PATH/
    - ssh $DEPLOY_SERVER "cd $DEPLOY_PATH && ./deploy.sh"
  environment:
    name: dev
  # only:
  #   - dev
  tags:
    - blurrr-deploy