stages:
  - build

build:
  stage: build
  image: gradle:6.9.3-jdk17
  only:
    - cicd-test
  before_script:
    - echo 'build starts'
    - chmod +x ./backend/blur/gradlew
    # - cp $SECURE_FILES/application.yml ./backend/blur/src/main/resources/application.yml
    # - cp $SECURE_FILES/application-jwt.yml ./backend/blur/src/main/resources/application-jwt.yml
    # - cp $SECURE_FILES/application-dev.yml ./backend/blur/src/main/resources/application-dev.yml
    # - cp $SECURE_FILES/application-email.yml ./backend/blur/src/main/resources/application-email.yml
    # - cp $SECURE_FILES/application-aws.yml ./backend/blur/src/main/resources/application-aws.yml

  script:
    - ./backend/blur/gradlew clean build
  artifacts:
    paths:
      - ./backend/blur/build/libs/*.jar
    expire_in: 1 week 
  tags:
    - test-deploy