image: ubuntu:22.04

include:
    - local: '/deploy/server-dev.yml'
    - local: '/deploy/client-dev.yml'
    # - local: '/deploy/server-prod.yml'
    # - local: '/deploy/client-prod.yml'

stages:
    - frontend-build
    - frontend-deploy
    - backend-build
    - backend-deploy

before_script:
    - apt-get update || { echo "apt-get update failed"; exit 1; }
