spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mysql://localhost:13306/jpa_demo
#    username: root
#    password: tkdgus1234

server:
  port: 8080
