spring:
  application:
    name: blur

  profiles:
    default: local
    include: private

  datasource:
    p6spy:
      enable-logging: true
      multiline: true
      logging: slf4j
      tracing:
        include-parameter-values: true


server:
  port: 8080
