spring:
  config:
    activate:
      on-profile: local

  jpa:
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console

#  datasource:
#    url: jdbc:mariadb://localhost:3306/blur
#    driver-class-name: org.mariadb.jdbc.Driver
#    username: root
#    password: blurr123
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:test
#    username: sa
#    password:

  docker:
    compose:
      lifecycle-management: start_and_stop
      enabled: true
      stop:
        command: down

server:
  port: 8080

jwt:
  secret: dGVhbWJsdXJyLWp3dC10b2tlbi1zc2FmeTExdGgtYTMwNy1yYW5kb21SdHJpbmc6ajFENVNiMWozampzTmtuNTU0
  expire:
    time:
      access: 60000
      refresh: 120000
