services:
  redis:
    image: 'redis:latest'
    ports:
      - "6379:6379"

  mariadb:
    image: 'mariadb:latest'
    environment:
      - 'MARIADB_DATABASE=blur'
      - 'MARIADB_PASSWORD=secret'
      - 'MARIADB_ROOT_PASSWORD=blurr123'
      - 'MARIADB_USER=blur'
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
